# docker-compose.yml

version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map server port
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/usr/src/app  # Mount code for live reload (optional)

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map client port
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/usr/src/app  # Mount code for live reload (optional)
